[env:esp32] ; your esp32 board
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps = 
	https://github.com/Links2004/arduinoWebSockets.git
	bblanchon/ArduinoJson @ ^7.0.0
	fastled/FastLED@^3.10.3
  

[env:esp8266] ; esp8266 for alternative
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
lib_deps = 
  https://github.com/Links2004/arduinoWebSockets.git
  bblanchon/ArduinoJson @ ^7.0.0
  fastled/FastLED@^3.10.3